### ISSUE TITLE
Deserialization fails for unknown field of type integer 

### ISSUE THREAD

**Issue by Javatar81** [kiota-community/kiota-java-extra#141]
The deserialization of the following json string with an unknown field of type integer:

```json
{"string":"I am a string","integer":1,"unknownint":2}
```

Leads to runtime exception:

```java
Exception in thread "main" java.lang.RuntimeException: Could not get the value during deserialization, unknown primitive type
	at io.kiota.serialization.json.JsonParseNode.tryGetAnything(JsonParseNode.java:320)
	at io.kiota.serialization.json.JsonParseNode.assignFieldValues(JsonParseNode.java:302)
	at io.kiota.serialization.json.JsonParseNode.getObjectValue(JsonParseNode.java:248)
	at org.operator.gen.v1alpha1.KiotaTest.main(KiotaTest.java:15)
```

**Comment by andreaTP** [comment]
Fixed in #142
